name: learn-anything.xyz
description: The blog
meta_description: "You can learn anything"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://learn-anything.github.io'
google_analytics: 'UA-74470910-3'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Team'
