name: Learn Anything
description: Exposing as much of human knowledge in a visual and structured way as possible to accelerate learning
meta_description: "Learn anything"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://learn-anything.github.io'
google_analytics: 'UA-74470910-3'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'blog url'
author:         'Team'
